import type { CSSProperties } from 'react'
import {
  Activity,
  AlertCircle,
  AlertTriangle,
  ArrowDown,
  ArrowDownLeft,
  ArrowDownRight,
  ArrowLeft,
  ArrowLeftRight,
  ArrowRight,
  ArrowUp,
  ArrowUpDown,
  ArrowUpRight,
  Banknote,
  BarChart3,
  Bell,
  Bitcoin,
  Building2,
  Bus,
  CalendarDays,
  CandlestickChart,
  Car,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ClipboardCheck,
  Clock,
  Cloud,
  CloudOff,
  Coins,
  Command,
  Copy,
  Cpu,
  CreditCard,
  Download,
  Droplet,
  Dumbbell,
  ExternalLink,
  Eye,
  EyeOff,
  Factory,
  FileText,
  Film,
  Fingerprint,
  Flag,
  Gavel,
  Gem,
  Gift,
  Globe,
  GraduationCap,
  Home,
  Info,
  KeyRound,
  Landmark,
  LayoutGrid,
  Lightbulb,
  LineChart,
  Link,
  Lock,
  LogOut,
  Mail,
  Menu,
  Minus,
  MoreHorizontal,
  Package,
  Pencil,
  Percent,
  PieChart,
  PiggyBank,
  Plus,
  Receipt,
  RefreshCw,
  Repeat,
  Scale,
  ScanLine,
  Search,
  Send,
  Settings,
  Share,
  ShieldCheck,
  ShoppingBag,
  ShoppingBasket,
  ShoppingCart,
  SlidersHorizontal,
  Smartphone,
  Sprout,
  Stethoscope,
  Tag,
  TrendingUp,
  Upload,
  User,
  Utensils,
  Wallet,
  X,
  Zap,
  type LucideIcon,
} from 'lucide-react'
import type { IconName } from './icons'

/**
 * The icon map keeps its semantic names (`ICONS.nav.overview` is still
 * 'home'); this table says which stroke glyph each one draws. Lucide's
 * 24-grid, 1.75 px stroke reads close to SF Symbols at regular weight.
 */
const GLYPHS: Record<IconName, LucideIcon> = {
  home: Home,
  pie_chart: PieChart,
  public: Globe,
  swap_vert: ArrowUpDown,
  autorenew: Repeat,
  potted_plant: Sprout,
  monitoring: LineChart,
  receipt_long: Receipt,
  link: Link,
  flag: Flag,
  show_chart: TrendingUp,
  payments: Banknote,
  token: Coins,
  currency_bitcoin: Bitcoin,
  savings: PiggyBank,
  diamond: Gem,
  account_balance: Landmark,
  candlestick_chart: CandlestickChart,
  key: KeyRound,
  currency_exchange: ArrowLeftRight,
  real_estate_agent: Building2,
  directions_car: Car,
  credit_card: CreditCard,
  upload_file: Upload,
  shopping_cart: ShoppingCart,
  sell: Tag,
  redeem: Gift,
  percent: Percent,
  swap_horiz: ArrowLeftRight,
  call_received: ArrowDownLeft,
  call_made: ArrowUpRight,
  local_atm: Banknote,
  bolt: Zap,
  donut_small: PieChart,
  gavel: Gavel,
  credit_card_off: CreditCard,
  content_copy: Copy,
  timeline: Activity,
  inventory_2: Package,
  balance: Scale,
  trending_up: TrendingUp,
  calendar_month: CalendarDays,
  schedule: Clock,
  paid: Coins,
  warning: AlertTriangle,
  info: Info,
  lightbulb: Lightbulb,
  account_balance_wallet: Wallet,
  water_drop: Droplet,
  south_west: ArrowDownLeft,
  north_east: ArrowUpRight,
  memory: Cpu,
  medical_services: Stethoscope,
  factory: Factory,
  shopping_basket: ShoppingBasket,
  shopping_bag: ShoppingBag,
  category: LayoutGrid,
  more_horiz: MoreHorizontal,
  request_quote: FileText,
  restaurant: Utensils,
  sports_tennis: Activity,
  health_and_safety: ShieldCheck,
  commute: Bus,
  movie: Film,
  smartphone: Smartphone,
  fitness_center: Dumbbell,
  cloud: Cloud,
  cloud_done: CheckCircle2,
  sync: RefreshCw,
  sync_problem: AlertCircle,
  cloud_off: CloudOff,
  check_circle: CheckCircle2,
  error: AlertCircle,
  verified_user: ShieldCheck,
  arrow_drop_up: ChevronUp,
  arrow_drop_down: ChevronDown,
  add: Plus,
  search: Search,
  tune: SlidersHorizontal,
  ios_share: Share,
  download: Download,
  edit: Pencil,
  qr_code_scanner: ScanLine,
  passkey: Fingerprint,
  fact_check: ClipboardCheck,
  mail: Mail,
  forward_to_inbox: Send,
  sort: ArrowUpDown,
  school: GraduationCap,
  arrow_back: ArrowLeft,
  arrow_forward: ArrowRight,
  arrow_upward: ArrowUp,
  arrow_downward: ArrowDown,
  chevron_left: ChevronLeft,
  chevron_right: ChevronRight,
  expand_more: ChevronDown,
  expand_less: ChevronUp,
  close: X,
  check: Check,
  remove: Minus,
  menu: Menu,
  settings: Settings,
  notifications: Bell,
  visibility: Eye,
  visibility_off: EyeOff,
  open_in_new: ExternalLink,
  refresh: RefreshCw,
  logout: LogOut,
  person: User,
  lock: Lock,
  keyboard_command_key: Command,
  south_east: ArrowDownRight,
  looks_one: BarChart3,
  looks_two: BarChart3,
  looks_3: BarChart3,
}

interface IconProps {
  name: IconName
  /** Pixel size on the 24 px grid. Never under 14. */
  size?: number
  /** Heavier stroke when the control is active or selected. */
  filled?: boolean
  /** Required on an icon that stands alone. Decorative icons beside text leave it out and are hidden from readers. */
  label?: string
  className?: string
  style?: CSSProperties
}

/** A stroke glyph. Colour inherits from the text around it; weight follows `filled`. */
export function Icon({ name, size = 20, filled = false, label, className, style }: IconProps) {
  const Glyph = GLYPHS[name] ?? MoreHorizontal
  const px = Math.max(14, size)
  return (
    <span
      className={`wh-icon${filled ? ' fill' : ''}${className ? ` ${className}` : ''}`}
      role={label ? 'img' : undefined}
      aria-label={label}
      aria-hidden={label ? undefined : true}
      style={{ width: px, height: px, fontSize: px, ...style }}
    >
      <Glyph size={px} strokeWidth={filled ? 2.25 : 1.75} absoluteStrokeWidth={false} aria-hidden="true" focusable="false" />
    </span>
  )
}
