/**
 * Fetches the fallback text face once from Google Fonts and self-hosts it:
 *   public/wh/fonts/*.woff2 and src/wh/fonts.css (generated).
 *
 * The product sets in the system UI face first (SF Pro on Apple platforms,
 * Segoe UI on Windows); Inter is the fallback that keeps the same optical
 * character everywhere else. Re-run:  node scripts/fetch-fonts.mjs
 */
import { mkdir, readdir, rm, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const client = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const OUT_DIR = path.join(client, 'public', 'wh', 'fonts')
const OUT_CSS = path.join(client, 'src', 'wh', 'fonts.css')
const UA =
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36'

const FAMILIES = [{ id: 'inter', query: 'family=Inter:opsz,wght@14..32,400..700&display=swap' }]
/** Subsets worth shipping: everything the ledger, names and currencies need. */
const SUBSETS = new Set(['latin', 'latin-ext'])

async function get(url) {
  const res = await fetch(url, { headers: { 'user-agent': UA } })
  if (!res.ok) throw new Error(`${res.status} ${url}`)
  return res
}

await mkdir(OUT_DIR, { recursive: true })
for (const old of await readdir(OUT_DIR)) if (old.endsWith('.woff2')) await rm(path.join(OUT_DIR, old))

const faces = []
for (const f of FAMILIES) {
  const css = await (await get(`https://fonts.googleapis.com/css2?${f.query}`)).text()
  const blocks = css.matchAll(/(?:\/\*\s*([a-z-]+)\s*\*\/\s*)?@font-face\s*\{([^}]*)\}/g)
  for (const [, subset, body] of blocks) {
    if (subset && !SUBSETS.has(subset)) continue
    const prop = (name) => body.match(new RegExp(`${name}:\\s*([^;]+);`))?.[1].trim()
    const family = prop('font-family')
    const style = prop('font-style') ?? 'normal'
    const weight = prop('font-weight') ?? '400'
    const range = prop('unicode-range')
    const url = body.match(/url\(([^)]+)\)/)?.[1]
    if (!family || !url) continue
    const file = [f.id, style === 'italic' ? 'italic' : null, subset ?? null].filter(Boolean).join('-') + '.woff2'
    const bytes = new Uint8Array(await (await get(url)).arrayBuffer())
    await writeFile(path.join(OUT_DIR, file), bytes)
    faces.push(
      [
        '@font-face {',
        `  font-family: ${family};`,
        `  font-style: ${style};`,
        `  font-weight: ${weight};`,
        '  font-display: swap;',
        `  src: url(/wh/fonts/${file}) format('woff2');`,
        range ? `  unicode-range: ${range};` : null,
        '}',
      ]
        .filter(Boolean)
        .join('\n'),
    )
    console.log(`${file}  ${(bytes.length / 1024).toFixed(1)} kB`)
  }
}

const header = `/* Generated by scripts/fetch-fonts.mjs. Do not edit by hand; re-run the script.
   Inter: SIL Open Font License 1.1. Served as the fallback behind the system UI face. */\n`
await writeFile(OUT_CSS, header + faces.join('\n') + '\n')
console.log(`wrote ${path.relative(client, OUT_CSS)} with ${faces.length} faces`)
