/**
 * Fetches the brand fonts once from Google Fonts and self-hosts them:
 *   public/wh/fonts/*.woff2 and src/wh/fonts.css (generated).
 * DM Sans and Instrument Serif are complete latin + latin-ext cuts. Material
 * Symbols Rounded is subset to the names in src/wh/icons.ts, so re-run this
 * after adding an icon there:  node scripts/fetch-fonts.mjs
 */
import { mkdir, readFile, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const client = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const OUT_DIR = path.join(client, 'public', 'wh', 'fonts')
const OUT_CSS = path.join(client, 'src', 'wh', 'fonts.css')
const UA =
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36'

const iconsSource = await readFile(path.join(client, 'src', 'wh', 'icons.ts'), 'utf8')
const iconNames = [...new Set([...iconsSource.matchAll(/:\s*'([a-z][a-z0-9_]*)'/g)].map((m) => m[1]))].sort()

const FAMILIES = [
  { id: 'dm-sans', query: 'family=DM+Sans:opsz,wght@9..40,400..700&display=swap' },
  { id: 'instrument-serif', query: 'family=Instrument+Serif:ital@0;1&display=swap' },
  {
    id: 'material-symbols-rounded',
    query: `family=Material+Symbols+Rounded:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200&icon_names=${iconNames.join(',')}&display=block`,
  },
]

async function get(url) {
  const res = await fetch(url, { headers: { 'user-agent': UA } })
  if (!res.ok) throw new Error(`${res.status} ${url}`)
  return res
}

await mkdir(OUT_DIR, { recursive: true })
const faces = []
for (const f of FAMILIES) {
  const css = await (await get(`https://fonts.googleapis.com/css2?${f.query}`)).text()
  const blocks = css.matchAll(/(?:\/\*\s*([a-z-]+)\s*\*\/\s*)?@font-face\s*\{([^}]*)\}/g)
  for (const [, subset, body] of blocks) {
    const prop = (name) => body.match(new RegExp(`${name}:\\s*([^;]+);`))?.[1].trim()
    const family = prop('font-family')
    const style = prop('font-style') ?? 'normal'
    const weight = prop('font-weight') ?? '400'
    const display = prop('font-display') ?? 'swap'
    const range = prop('unicode-range')
    const url = body.match(/url\(([^)]+)\)/)?.[1]
    if (!family || !url) continue
    const file = [f.id, style === 'italic' ? 'italic' : null, subset ?? null].filter(Boolean).join('-') + '.woff2'
    const bytes = new Uint8Array(await (await get(url)).arrayBuffer())
    await writeFile(path.join(OUT_DIR, file), bytes)
    faces.push(
      [
        '@font-face {',
        `  font-family: ${family};`,
        `  font-style: ${style};`,
        `  font-weight: ${weight};`,
        `  font-display: ${display};`,
        `  src: url(/wh/fonts/${file}) format('woff2');`,
        range ? `  unicode-range: ${range};` : null,
        '}',
      ]
        .filter(Boolean)
        .join('\n'),
    )
    console.log(`${file}  ${(bytes.length / 1024).toFixed(1)} kB`)
  }
}

const header = `/* Generated by scripts/fetch-fonts.mjs. Do not edit by hand; re-run the script.
   DM Sans and Instrument Serif: SIL Open Font License 1.1. Material Symbols Rounded: Apache License 2.0,
   subset to the ${iconNames.length} names in src/wh/icons.ts. */\n`
await writeFile(OUT_CSS, header + faces.join('\n') + '\n')
console.log(`wrote ${path.relative(client, OUT_CSS)} with ${faces.length} faces`)
